### ISSUE TITLE
Undefined array key "targetID" in functionalphp\admin-modify-account.php

### ISSUE THREAD

**Issue by Michelle5757** [vinesmsuic/Online-Examination-System#2]
As an admin, I can't modify the student or teacher account details, I always receive this error:
![image](https://user-images.githubusercontent.com/77832753/105491170-90ee2580-5cbe-11eb-932c-72f24adbac67.png)
and the data from the form it's suddenly lost. 
The database's correctly setup, so it's no problem with this

**Comment by vinesmsuic** [comment]
Not sure why this happens on your machine. Can you provide more detail?
OS, Browser version, the detailed error log etc

**Comment by Michelle5757** [comment]
Hello, Windows 10, Chrome or Firefox, still got the same error on any browser. Basically, what I've tried was to edit a student/teacher as an admin, and I faced this error.

**Comment by vinesmsuic** [comment]
1. Did you login admin account with the given account "admin"?
2. So you encounter this error after clicking the "MODIFY" button?
3. Can you provide a detailed error log of both `functionalphp\admin-modify-account.php` and `page\admin-modify-account.php` ?

**Comment by Michelle5757** [comment]
Yes, I've logged in using the admin user. I encounter this error after clicking the save button on the modify page. On the console I only have that error ,, Undefined array key "targetID" in functionalphp\admin-modify-account.php"

**Comment by Michelle5757** [comment]
Also, I've found that if you disconnect, and you try to login again after 2-3 sec, it will not work, you need to wait for a few seconds to login again

**Comment by Michelle5757** [comment]
You have this function: TimeoutAndRedirect() that it's causing the high loading time on a server, you need to refactor a lot the code...

**Comment by Michelle5757** [comment]
Also, what I've noticed is that you're using cookies for login, which it's not the most effective method.. When you refactor your code try to use $_SESSION in order to not have problems at login

**Comment by Michelle5757** [comment]
I've proposed to you some changes, try to test it please and see the result

**Comment by Michelle5757** [comment]
Also, try to rethink the timeoutandredirect function cause it's not OK if you try to use it for example on a server

**Comment by Michelle5757** [comment]
Also, for password, try to use hashes, it is a much better way. Check here: https://stackoverflow.com/questions/30279321/how-to-use-phps-password-hash-to-hash-and-verify-passwords

**Comment by vinesmsuic** [comment]
This repo is actually my uni yr3 homework project. If I have time I will try to improve it. My classmate is reviewing the pull request.

**Comment by Michelle5757** [comment]
Wow, Really nice project, congrats! The only part that needs, let's say, to urgently be done, it's the admin part where you can edit users info, it's not working, not at all..

**Comment by Michelle5757** [comment]
I can talk with your buddy if he needs some help in doing this, I'll push some requests in order for him to test it, and give a feedback

**Comment by ZXTHR** [comment]
Hi, I never thought I would work on this project again, but I guess I am here now :^)
I have tried to use hash password instead, one problem is that if I were to save the hashed password into the database, then we would not be able to show it in the admin management page, as it seems that there is no way to unhash the password. So either we have to not use this method, or just abandon the password column(which will be problematic in modify-account page, as the original password of the account is supposed to be auto written into the field for admin to see as a reference. Since viewing the original password is not possible, an extra button would need to be added for the password column alone, just like the profile image, so admin either choose to change the password or keep the original one(without knowing what the original one is).)
As for using session instead of cookie, one of the reason we decided to use cookie is that it can deal with auto logout by inactivity easily. I have changed my version of code into using session, but it seems that it has lost this function. One way to implement it back that I can think of is to record the time in your computer and save it as a session variable, compare the real time with the recorded one and exchange with the new time everytime the user change the page. However I heard that the php code concerning about time do not work in your computer due to the timezone problem, so I decided not to work on it(also because I am kinda lazy xD).
Speak of the timezone problem, I have searched for some methods to obtain the correct timezone from user's computer, but I haven't find any valid solution yet. To be honest, unless there is a clear solution, I lack of interest to fix this for now, so sorry I guess. I would suggest you to change "Asia/Hong Kong" in the php code to the region you are in, as I suppose you won't be using this code in an international school right?
I assume timeoutandredirect causing delay because of the ajax stuff, so instead of using timeoutandredirect, i simply implemented redirect.php into mainhead.php and have it auto check user . Though I personally don't feel any delay beforehand, so I can't really see if it makes any difference.
As for the modify account problem, I cannot really find whats the problem as I have never encountered this myself. By any chance you have any plugin which stops the javascript from working? The "targetID" is input into as $_POST variable when you click the modify button next to an account row in management page, then submit to the modify account page. For now I can't think of a way to fix this. Maybe using session variable instead of form variable would make a change, but I do not know how to do it.
I haven't encounter the disconnect-and-login-delay issue after(and before) updating the code, so I would suggest you to try it for yourself.
I have uploaded a new version, which is basically using session variables instead, hashpassword(the admin issues not fixed yet, in case you have any suggestion of making it better in some way) and using redirect.php over javascript method "timeoutandredirect". Also the password field in database is changed to a larger capacity. Nothing else has changed(Though it shown that it is since I messed up the way to use github again. My bad.) There maybe hidden problems, feel free to let us know! (Though I doubt if we would have time to work on it, since we also have other things to work on :\)

**Comment by Michelle5757** [comment]
Hello, I have tried to use in on a domain and not on localhost and I'm facing issues with login(AJAX can't process so many requests, I can change the password, create an account, but I can't logout, then log in, and sometimes I can't even login). I don't have and plugin that stops javascript from running, because, as I've said, register/change password works just fine, only the login it's the problem and the admin part. 
I can also help you with this project, no problem

**Comment by Michelle5757** [comment]
Hello, I have some recommendations for you.
Instead of going back and forth just redirect the user to the relevant page in one go:
username + pass -> backend -> relevant page. So instead of returning the user type the backend will return the correct page.

**Comment by Michelle5757** [comment]
As for admin password, it should be without seeing the password. If you want to administer the account then you do not need its password. And if you want to change the password then just use some button/box for generating new password. Admins should not see passwords either.

**Comment by vinesmsuic** [comment]
closing this issue

**Comment by Michelle5757** [comment]
The admin it's now working perfectly for me, I can change the passwords, so basically this error it's happening from system to system...

**Comment by vinesmsuic** [comment]
@Michelle5757 hi, what system infrastructure are you using?

**Comment by Michelle5757** [comment]
Hi! I've tested on both localhost using xampp, and also on the free tire of Hostinger

**Comment by vinesmsuic** [comment]
Localhost using Xampp should work fine. Never used it on a hosting service.
May I know what kind of project are you working on so you need to test this site?
If you are working on a business project, I think it is not that suitable to borrow code from our site (because student projects usually can't fulfill the business requirements, a lot of bugs and not maintained).

**Comment by Michelle5757** [comment]
It's not a business project, otherwise, I'll not be here. I'm just testing various projects on Github. Basically what I want to do it's to help you improve your project
